// weekly-review.js — 周回顾生成器：聚合待办 / 专注 / 习惯 / 笔记动态，
// 一键生成一篇周回顾笔记到 _daily/。纯本地计算，不依赖网络与 AI。

const REVIEW_DIR = DAILY_DIR;

// 计算回顾区间：
// - lastWeek：上一个完整自然周（周一 ~ 周日，ISO 周）
// - thisWeek：本周一 ~ 今天
function resolveWeeklyRange(mode, now) {
  const monday = now.clone().startOf('isoWeek');
  if (mode === 'thisWeek') return { start:monday.clone(), end:now.clone(), label:mode };
  const start = monday.clone().subtract(7, 'day');
  return { start, end:start.clone().add(6, 'day').endOf('day'), label:'lastWeek' };
}

function formatRangeHeading(range, lang) {
  const en = lang === 'en';
  const fmt = (d) => en ? d.format('MMM D') : d.format('M月D日');
  return fmt(range.start.clone()) + ' – ' + fmt(range.end.clone().startOf('day'));
}

function weekKeyOf(momentValue) {
  return momentValue.isoWeekYear() + '-W' + String(momentValue.isoWeek()).padStart(2, '0');
}

function collectWeeklyReviewStats({ todos = [], focusHistory = null, habits = [], files = [], range }) {
  const start = range.start.clone().startOf('day');
  const end = range.end.clone().endOf('day');
  const inRange = (value) => value && value.valueOf() >= start.valueOf() && value.valueOf() <= end.valueOf();
  const dayKeys = [];
  {
    let cursor = start.clone();
    while (cursor.valueOf() <= end.valueOf()) { dayKeys.push(cursor.format('YYYY-MM-DD')); cursor = cursor.add(1, 'day'); }
  }

  const completed = todos
    .filter((todo) => todo.done && inRange(todo.doneDate))
    .slice()
    .sort((a, b) => (a.doneDate?.valueOf() || 0) - (b.doneDate?.valueOf() || 0));
  const created = todos.filter((todo) => inRange(todo.created));
  const openOverdue = todos.filter((todo) => !todo.done && todo.dueDate && todo.dueDate.valueOf() < window.moment().startOf('day').valueOf());

  const focusByDay = dayKeys.map((key) => ({ key, minutes:(focusHistory && focusHistory.get) ? (focusHistory.get(key) || 0) : 0 }));
  const focusTotal = focusByDay.reduce((sum, day) => sum + day.minutes, 0);

  const today = window.moment();
  const habitLines = habits.map((habit) => {
    const log = Array.isArray(habit.log) ? habit.log : [];
    const set = new Set(log);
    const daysDone = dayKeys.filter((key) => set.has(key)).length;
    return { name:habit.name, icon:habit.icon || '🔥', daysDone, total:dayKeys.length, streak:computeStreak(log, today) };
  });

  const mdFiles = files.filter((file) => file.extension === 'md');
  const notesCreated = mdFiles.filter((file) => file.stat && file.stat.ctime >= start.valueOf() && file.stat.ctime <= end.valueOf());
  const notesEdited = mdFiles.filter((file) => file.stat && file.stat.mtime >= start.valueOf() && file.stat.mtime <= end.valueOf())
    .slice().sort((a, b) => b.stat.mtime - a.stat.mtime);

  return { completed, created, openOverdue, focusByDay, focusTotal, habitLines, notesCreated, notesEdited, dayKeys };
}

function formatWeeklyReviewMarkdown(stats, { lang, range, weekKey, generatedAt }) {
  const en = lang === 'en';
  const fmtDay = (momentValue) => en ? momentValue.format('MMM D') : momentValue.format('M月D日');
  const wikiLink = (path) => '[[' + String(path || '').replace(/(\||\]\])/g, ' ').trim() + '|' + (String(path).split('/').pop() || '').replace(/\.md$/i, '') + ']]';
  const lines = [];

  lines.push('# ' + (en ? 'Weekly Review' : '周回顾') + ' · ' + weekKey + '（' + formatRangeHeading(range, lang) + '）');
  lines.push('');
  lines.push('> ' + (en ? 'Generated by Cockpit Dashboard at ' : '由 Cockpit Dashboard 生成于 ') + generatedAt.format(en ? 'YYYY-MM-DD HH:mm' : 'YYYY-MM-DD HH:mm'));
  lines.push('');

  // 概览
  const activeDays = stats.focusByDay.filter((day) => day.minutes > 0).length;
  const habitTotalDone = stats.habitLines.reduce((sum, item) => sum + item.daysDone, 0);
  lines.push('## ' + (en ? 'Overview' : '概览'));
  lines.push('- ✅ ' + (en ? 'Tasks completed: ' : '完成待办：') + stats.completed.length + (en ? '' : ' 项'));
  lines.push('- 🆕 ' + (en ? 'Tasks created: ' : '新增待办：') + stats.created.length + (en ? '' : ' 项'));
  lines.push('- ⚠️ ' + (en ? 'Still overdue: ' : '当前逾期未清：') + stats.openOverdue.length + (en ? '' : ' 项'));
  lines.push('- 🍅 ' + (en ? 'Focus time: ' : '专注时长：') + stats.focusTotal + ' min' + (en ? (' across ' + activeDays + ' active day(s)') : ('（有专注记录 ' + activeDays + ' 天）')));
  lines.push('- 🔥 ' + (en ? 'Habit check-ins: ' : '习惯打卡合计：') + habitTotalDone + (stats.habitLines.length ? (en ? ' across ' + stats.habitLines.length + ' habit(s)' : ' 次（共 ' + stats.habitLines.length + ' 个习惯）') : ''));
  lines.push('- ✏️ ' + (en ? 'Notes: ' : '笔记动态：') + (en ? 'created ' + stats.notesCreated.length + ', edited ' + stats.notesEdited.length : '新建 ' + stats.notesCreated.length + ' 篇 · 编辑 ' + stats.notesEdited.length + ' 篇'));
  lines.push('');

  // 完成的待办
  lines.push('## ' + (en ? 'Completed tasks' : '完成的待办'));
  if (!stats.completed.length) lines.push((en ? '- Nothing completed this period yet.' : '- 这个周期还没有已完成的待办。'));
  else stats.completed.forEach((todo) => lines.push('- [x] ' + todo.text + (en ? ' （done ' : '（') + fmtDay(todo.doneDate) + (en ? ')' : ' 完成）')));
  lines.push('');

  // 未完成与逾期
  lines.push('## ' + (en ? 'Open & overdue' : '未完成 / 逾期'));
  if (!stats.openOverdue.length) lines.push((en ? '- No overdue tasks. Keep it clean ✦' : '- 没有逾期待办，保持住 ✦'));
  else stats.openOverdue.slice(0, 15).forEach((todo) => lines.push('- [ ] ' + todo.text + (en ? ' （due ' : '（截止 ') + fmtDay(todo.dueDate) + '）'));
  lines.push('');

  // 专注趋势
  lines.push('## ' + (en ? 'Focus trend' : '专注趋势'));
  const maxMinutes = Math.max(1, ...stats.focusByDay.map((day) => day.minutes));
  stats.focusByDay.forEach((day) => {
    const barLength = Math.round(day.minutes / maxMinutes * 12);
    const bar = barLength > 0 ? '▇'.repeat(barLength) : '·';
    lines.push('- ' + day.key.slice(5) + '　' + bar + '　' + day.minutes + ' min');
  });
  lines.push('');

  // 习惯打卡
  lines.push('## ' + (en ? 'Habits' : '习惯打卡'));
  if (!stats.habitLines.length) lines.push((en ? '- No habits tracked yet.' : '- 还没有在跟踪的习惯。'));
  else stats.habitLines.forEach((item) => lines.push('- ' + item.icon + ' ' + item.name + '：' + item.daysDone + '/' + item.total + (en ? ' day(s)' : ' 天') + (item.streak > 0 ? (en ? ' · streak ' + item.streak : ' · 当前连胜 ' + item.streak + ' 天') : '')));
  lines.push('');

  // 笔记动态
  lines.push('## ' + (en ? 'Note activity' : '笔记动态'));
  if (stats.notesCreated.length) {
    lines.push((en ? '**Created**' : '**新建**'));
    stats.notesCreated.slice(0, 8).forEach((file) => lines.push('- ' + wikiLink(file.path)));
    lines.push('');
  }
  if (stats.notesEdited.length) {
    lines.push((en ? '**Most recently edited**' : '**最近编辑**'));
    stats.notesEdited.slice(0, 8).forEach((file) => lines.push('- ' + wikiLink(file.path)));
    lines.push('');
  }
  if (!stats.notesCreated.length && !stats.notesEdited.length) lines.push((en ? '- No note activity this period.' : '- 这个周期没有笔记编辑记录。'));

  lines.push('## ' + (en ? 'Reflection' : '小结'));
  lines.push((en ? '- What went well this week?' : '- 这周做得最好的事是什么？'));
  lines.push((en ? '- What to carry into next week?' : '- 下周要延续或改进什么？'));
  lines.push('');

  return lines.join('\n');
}

async function buildWeeklyReviewModule(view, root) {
  const en = view._lang() === 'en';

  // 用裸文本节点承载标题，保证「编辑模式里重命名模块标题」对本周卡同样生效。
  const title = root.createDiv({ cls: PLUGIN_ID + '-section-title', text: view._t('sections.weeklyReview') });
  title.dataset.section = 'weekly-review-title';

  const body = root.createDiv({ cls: PLUGIN_ID + '-weekly-review' });
  body.dataset.section = 'weekly-review-body';

  let cachedStats = null;
  let cachedRange = null;
  let cachedWeekKey = '';

  const collect = async (rangeMode) => {
    const range = resolveWeeklyRange(rangeMode, window.moment());
    let habits = [];
    try { habits = await loadHabits(view.app.vault); } catch (e) { console.warn('Cockpit weekly review habit stats failed', e); }
    const stats = collectWeeklyReviewStats({
      todos:view._todos || [],
      focusHistory:view._focusHistory,
      habits,
      files:view.app.vault.getMarkdownFiles(),
      range
    });
    return { range, stats, weekKey:weekKeyOf(range.start) };
  };

  const findExistingFile = (weekKeyValue) => view.app.vault.getAbstractFileByPath(REVIEW_DIR + '/' + (en ? 'Weekly Review ' : '周回顾 ') + weekKeyValue + '.md');

  const generate = async () => {
    const data = cachedStats || await collect(cachedRange);
    const content = formatWeeklyReviewMarkdown(data.stats, {
      lang:en ? 'en' : 'zh-CN',
      range:data.range,
      weekKey:data.weekKey,
      generatedAt:window.moment()
    });
    const path = REVIEW_DIR + '/' + (en ? 'Weekly Review ' : '周回顾 ') + data.weekKey + '.md';
    try {
      if (!view.app.vault.getAbstractFileByPath(REVIEW_DIR)) await view.app.vault.createFolder(REVIEW_DIR);
      const existing = view.app.vault.getAbstractFileByPath(path);
      if (existing) await view.app.vault.modify(existing, content);
      else await view.app.vault.create(path, content);
      await view.app.workspace.getUnpinnedLeaf().setViewState({ type:'markdown', state:{ file:path } });
      new obs.Notice(en ? 'Weekly review saved to ' + path : '周回顾已保存到 ' + path);
    } catch (e) {
      console.warn('Cockpit weekly review save failed', e);
      new obs.Notice(en ? 'Could not save the weekly review.' : '周回顾保存失败。');
    }
  };

  const render = async () => {
    const mode = select.value === 'thisWeek' ? 'thisWeek' : 'lastWeek';
    const data = await collect(mode);
    cachedStats = data; cachedRange = mode; cachedWeekKey = data.weekKey;
    const stats = data.stats;
    summary.empty();
    const chips = [
      { icon:'✅', text:(en ? 'done ' : '完成 ') + stats.completed.length },
      { icon:'🆕', text:(en ? 'new ' : '新增 ') + stats.created.length },
      { icon:'⚠️', text:(en ? 'overdue ' : '逾期 ') + stats.openOverdue.length },
      { icon:'🍅', text:stats.focusTotal + ' min' },
      { icon:'🔥', text:stats.habitLines.reduce((sum, item) => sum + item.daysDone, 0) + (en ? ' check-ins' : ' 次打卡') }
    ];
    chips.forEach((chip) => summary.createDiv({ cls:PLUGIN_ID + '-review-chip', text:chip.icon + ' ' + chip.text }));
    hint.setText(formatRangeHeading(data.range, en ? 'en' : 'zh-CN') + ' · ' + data.weekKey + (findExistingFile(data.weekKey) ? (en ? ' · saved' : ' · 已生成') : ''));
  };

  const headRow = body.createDiv({ cls: PLUGIN_ID + '-review-head' });
  const summary = headRow.createDiv({ cls: PLUGIN_ID + '-review-chips' });
  const controls = headRow.createDiv({ cls: PLUGIN_ID + '-review-controls' });
  const select = controls.createEl('select', { attr: { type:'button', title:en?'Review range':'回顾区间' } });
  select.createEl('option', { text:en ? 'Last week' : '上周', attr:{ value:'lastWeek' } });
  select.createEl('option', { text:en ? 'This week' : '本周至今', attr:{ value:'thisWeek' } });
  const hint = controls.createSpan({ cls: PLUGIN_ID + '-review-hint' });
  const genBtn = controls.createEl('button', { cls: PLUGIN_ID + '-review-generate', text:en ? 'Generate review' : '生成周回顾', attr:{ type:'button' } });
  genBtn.onclick = async () => {
    genBtn.disabled = true;
    try { await generate(); }
    finally { genBtn.disabled = false; render().catch(() => {}); }
  };
  select.onchange = () => render().catch((e) => console.warn('Cockpit weekly review render failed', e));

  view._refreshWeeklyReviewRef = render;
  try { await render(); } catch (e) { console.warn('Cockpit weekly review failed; dashboard basics remain available', e); }
  view._makeModuleCollapsible('weeklyReview', title, body);
  return render;
}
